version: "2"
services:
    nginx_firstapp:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./media:/media
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - flask
    redis:
        image: redis:2.8.19
        hostname: redis

    flask:
        build: .
        hostname: "${PROJECT_NAME}_flask"
        container_name: "${PROJECT_NAME}_flask"
        command: bash -c "flask run --host=0.0.0.0 --port=80"
        volumes:
            - ./src:/src
            - ./media:/media
        expose:
            - "80"
        links:
            - mysql:mysql
            - redis:redis
        depends_on:
            - mysql
            - redis
        environment:
            - C_FORCE_ROOT=true
            - APP_CONFIG_FILE=/src/${PROJECT_NAME}/config/local.py
            - FLASK_APP=${PROJECT_NAME}
            - FLASK_DEBUG=1
    mysql:
        image: mysql:5.7
        volumes:
            - ./database/config:/etc/mysql/conf.d
            - ./database/data:/sqlfiles
            - ./database/datastructure:/var/lib/mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
        container_name: "${PROJECT_NAME}_db_mysql"
