"""empty message

Revision ID: 37a353bd1d43
Revises: 21d3894f599a
Create Date: 2018-05-31 17:45:25.271715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a353bd1d43'
down_revision = '21d3894f599a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    # ### end Alembic commands ###
