"""empty message

Revision ID: 6774b08d3711
Revises: 37a353bd1d43
Create Date: 2018-05-31 18:35:38.619137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6774b08d3711'
down_revision = '37a353bd1d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
