"""empty message

Revision ID: 79029ead276a
Revises: a3857f5cf650
Create Date: 2018-06-20 22:01:15.400236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79029ead276a'
down_revision = 'a3857f5cf650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('never_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'never_delete')
    # ### end Alembic commands ###
