"""empty message

Revision ID: a3857f5cf650
Revises: 145bdb8f19fc
Create Date: 2018-06-20 21:15:52.978211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3857f5cf650'
down_revision = '145bdb8f19fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_permissions', sa.Column('can_view', sa.Boolean(), nullable=True))
    op.drop_column('matrix_permissions', 'can_list')
    op.drop_column('matrix_permissions', 'can_retrieve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_permissions', sa.Column('can_retrieve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('matrix_permissions', sa.Column('can_list', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('matrix_permissions', 'can_view')
    # ### end Alembic commands ###
